version: "3.8"

services:
  service1:
    build: ./service_1
    ports:
      - "8001:8001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/ping"]
      interval: 10s
      retries: 3
    networks:
      - appnet

  service2:
    build: ./service_2
    ports:
      - "8002:8002"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/ping"]
      interval: 10s
      retries: 3
    networks:
      - appnet

  nginx:
    build: ./nginx
    ports:
      - "8083:80"
    depends_on:
      - service1
      - service2
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
